# inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'config/unicorn.rb'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
    - 'bin/*'
    - 'db/*'
    - 'Gemfile'

Style/Documentation:
  Enabled: false

Style/AlignHash:
  Enabled: false

Style/AlignParameters:
  Enabled: false
